---
global:
  data_path: './data/'
  session_flg: 0
onedrive:
  client_id: 
  client_secret: 
  redirect_url: 
dropbox:
  client_id: 
  client_secret: 
  redirect_url: 
googledrive:
  client_id: 
  client_secret: 
  redirect_url: 

